### PR TITLE
Update client.py

### PR DESCRIPTION
**Pull request by lhost25**
Here is it for the html msg.

### CODE REVIEW

**Review by mononobi — CHANGES_REQUESTED** [review]
Thanks for your work.

There are a couple of issues which need to be imporved:

1. please read `sender_name` from `senders.txt` file not from the email message file.
    because the app should work correctly if senders are more than one.
    the `senders.txt` file should have a template like this: 
    `sender_email_1@example.com[***]password_1[***]sender_name_1`
     note that the code should ignore the `sender_name` if it is not provided in `senders.txt`
     file, so it should be optional and if it's not provided the app should not raise error.
2. please change variable name `fromname` to `sender_name` everywhere.
3. the app should also handle plain text emails. this way it's always treated as html which is 
    not what's intended. so please change the template of `mail.txt` file to this:
    ```
    <<-html or text->>
    Email Subject Goes Here
  
    Email message to {name} goes here.
  
    It could have as many lines as you want with empty lines in between.
    Only the first line of this file will be considered as subject.

    it could also be an html message if the first line is set to <-html->.
  
    Have a nice day
    ```
   and then change the mail extractor to also consider the first line of `mail.txt` 
   as message type. then inside client `send` method, consider this type to find 
   out whether `subtype` should be passed to `set_content` or not.
4. please remove duplicate `msg.set_content()` calls inside client `send` method.

**Comment by lhost25** [comment]
Ok noted. but now i am having issues in reading sender_name from senders.txt.
@mononobi your update will be highly appreciated been as the owner.

**Comment by lhost25** [comment]
It will be perfect if you can pass the update on your git and edit the README on the new update sir.

You are such an amazing person and a good listener sir. @mononobi

**Comment by mononobi** [comment]
> Ok noted. but now i am having issues in reading sender_name from senders.txt. @mononobi your update will be highly appreciated been as the owner.

What do you mean by having issues reading it?
if you're saying that you can not change it, then I will change it later.

**Comment by mononobi** [comment]
> It will be perfect if you can pass the update on your git and edit the README on the new update sir.
> 
> You are such an amazing person and a good listener sir. @mononobi

OK, I will make required changes myself and close this MR.

**Comment by lhost25** [comment]
@mononobi good bro. i look forward to it.

**Comment by lhost25** [comment]
I am still finding it difficult to read sender name from senders.txt.

**Comment by mononobi** [comment]
> I am still finding it difficult to read sender name from senders.txt.

No worries, I will do it, then you can see how it works.

**Comment by lhost25** [comment]
> > I am still finding it difficult to read sender name from senders.txt.
> 
> No worries, I will do it, then you can see how it works.

I am actually learning python don't mind me and i will like to see what i am missing or not getting right. Thanks @mononobi

**Comment by mononobi** [comment]
> 

My pleasure. that's great.
If you want to better understand it, you should take a look at `str.split` function and see how it works.
it always returns a list of items splitted over a separator. it could return a list with a single item or a list with multiple 
items depending on the string you've called `split` on it and the separator you've passed to `split`.

**Comment by lhost25** [comment]
> Thanks for your work.
> 
> There are a couple of issues which need to be imporved:
> 
> 1. please read `sender_name` from `senders.txt` file not from the email message file.
>    because the app should work correctly if senders are more than one.
>    the `sender.txt` file should have a template like this:
>    `sender_email_1@example.com[***]password_1[***]sender_name_1`
>    note that the code should ignore the `sender_name` if it is not provided in `senders.txt`
>    file, so it should be optional and if it's not provided the app should not raise error.
> 2. please change variable name `fromname` to `sender_name` everywhere.
> 3. the app should also handle plain text emails. this way it's always treated as html which is
>    not what's intended. so please change the template of `mail.txt` file to this:
>    ```
>    <-html or text->
>    Email Subject Goes Here
>    
>    Email message to {name} goes here.
>    
>    It could have as many lines as you want with empty lines in between.
>    Only the first line of this file will be considered as subject.
>    
>    it could also be an html message if the first line is set to <-html->.
>    
>    Have a nice day
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    and then change the mail extractor to also consider the first line of `mail.txt`
>    as message type. then inside client `send` method, consider this type to find
>    out whether `subtype` should be passed to `set_content` or not.
> 4. please remove duplicate `msg.set_content()` calls inside client `send` method.


base on your details here, i followed all instructions like you've explained without any solution. Under senders.py i added a new parts..rstrip just to call sender name from senders.txt with no luck and to make it optional i don't think thats possible.

How did you achieve "<-html or text->" in message? I am new and i believe with a lot of reading and tutorial on how its done i will know a lot about python. Out of every coding lang i prefer python and node js over all.

@mononobi

**Comment by lhost25** [comment]
> > 
> 
> My pleasure. that's great. If you want to better understand it, you should take a look at `str.split` function and see how it works. it always returns a list of items splitted over a separator. it could return a list with a single item or a list with multiple items depending on the string you've called `split` on it and the separator you've passed to `split`.

I will try to read more of this. I appreciate you pushing me forward.

**Comment by mononobi** [comment]
This MR would be closed as this feature is now implemented and you can check it out.

**Pull request closed without merging**
